/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
	export interface GlobalComponents {
		AButton: (typeof import('@arco-design/web-vue'))['Button']
		ADivider: (typeof import('@arco-design/web-vue'))['Divider']
		AInput: (typeof import('@arco-design/web-vue'))['Input']
		AInputPassword: (typeof import('@arco-design/web-vue'))['InputPassword']
		ATable: (typeof import('@arco-design/web-vue'))['Table']
		RouterLink: (typeof import('vue-router'))['RouterLink']
		RouterView: (typeof import('vue-router'))['RouterView']
		SvgIcon: (typeof import('./src/components/SvgIcon/index.vue'))['default']
	}
}
